### ISSUE TITLE
Incorrect sensor return

### ISSUE THREAD

**Issue by StarsTesla** [StanfordVL/OmniGibson#301] opened 2023-10-24 02:47 UTC
Hello, I am using robot sensors to detect surrounding objects, boxes=self. robot. get_ OBS() ['Fetch: eyes_Camera_sensor_bbox_2d_right '], but I found that the returned Box and object name do not match correctly. This has caused problems with my application because I am unable to correctly recognize and process detected objects.

**Comment by cgokmen** [comment] 2023-10-24 04:23
I will be investigating this this week - what version of Isaac Sim are you on?

**Comment by StarsTesla** [comment] 2023-10-25 02:04
2022.0

**Comment by StarsTesla** [comment] 2023-10-25 02:04
> I will be investigating this this week - what version of Isaac Sim are you on?

2022.0

**Comment by cgokmen** [comment] 2024-01-16 00:43
Hi, can you give us a script that we can try out to reproduce this issue? We were unable to reproduce this. Sorry for the late response.

**Comment by cgokmen** [comment] 2024-01-16 00:43
(for OG team: this is related to #458 )

**Comment by ChengshuLi** [comment] 2024-09-23 20:31
Should be fixed now.

**Closed by ChengshuLi** 2024-09-23 20:31 UTC
Labels: bug
