### ISSUE TITLE
GUI does not show up when running example from docker

### ISSUE THREAD

**Issue by tony88k** [StanfordVL/OmniGibson#559] opened 2024-01-21 13:32 UTC
I followed [the installation instructions](https://behavior.stanford.edu/omnigibson/getting_started/installation.html#setup),
and set up the docker container. When running the example
```
python -m omnigibson.examples.scenes.scene_selector
```
From the doc's Troubleshooting section, looks like the Omniverse Launcher app should pop up.  However, this is not happening for me. Below is a dump of my terminal output.
```
[INFO] [omnigibson] ---------- Starting OmniGibson ----------
[Warning] [omni.isaac.kit.simulation_app] Modules: ['omnigibson', 'omnigibson.macros', 'omni', 'omni.kit.app._impl.telemetry_helpers'] were loaded before SimulationApp was started and might not be loaded correctly.
[Warning] [omni.isaac.kit.simulation_app] Please check to make sure no extra omniverse or pxr modules are imported before the call to SimulationApp(...)
Starting kit application with the following args:  ['/isaac-sim/exts/omni.isaac.kit/omni/isaac/kit/simulation_app.py', '/isaac-sim/apps/omni.isaac.sim.python.kit', '--/app/tokens/exe-path=/isaac-sim/kit', '--/persistent/app/viewport/displayOptions=3094', '--/rtx/materialDb/syncLoads=True', '--/rtx/hydra/materialSyncLoads=True--/omni.kit.plugin/syncUsdLoads=True', '--/app/renderer/resolution/width=1280', '--/app/renderer/resolution/height=720', '--/app/window/width=1440', '--/app/window/height=900', '--/renderer/multiGpu/enabled=False', '--/app/fastShutdown=True', '--ext-folder', '/isaac-sim/exts', '--ext-folder', '/isaac-sim/apps', '--/physics/cudaDevice=0', '--portable', '--no-window', '--allow-root']
Passing the following args to the base kit application:  []
[Warning] [omni.kit.app.plugin] No crash reporter present, dumps uploading isn't available.
[Info] [carb] Logging to file: /isaac-sim/kit/logs/Kit/Isaac-Sim/2022.2/kit_20240121_131643.log
2024-01-21 13:16:43 [1ms] [Warning] [omni.ext.plugin] [ext: omni.drivesim.sensors.nv.lidar] Extensions config 'extension.toml' doesn't exist '/isaac-sim/exts/omni.drivesim.sensors.nv.lidar' or '/isaac-sim/exts/omni.drivesim.sensors.nv.lidar/config'
2024-01-21 13:16:43 [2ms] [Warning] [omni.ext.plugin] [ext: omni.drivesim.sensors.nv.radar] Extensions config 'extension.toml' doesn't exist '/isaac-sim/exts/omni.drivesim.sensors.nv.radar' or '/isaac-sim/exts/omni.drivesim.sensors.nv.radar/config'
[0.133s] [ext: omni.stats-0.0.0] startup
[0.164s] [ext: omni.rtx.shadercache-1.0.0] startup
[0.170s] [ext: omni.assets.plugins-0.0.0] startup
[0.172s] [ext: omni.gpu_foundation-0.0.0] startup
2024-01-21 13:16:43 [164ms] [Warning] [carb] FrameworkImpl::setDefaultPlugin(client: omni.gpu_foundation_factory.plugin, desc : [carb::graphics::Graphics v2.11], plugin : carb.graphics-vulkan.plugin) failed. Plugin selection is locked, because the interface was previously acquired by: 
[0.182s] [ext: carb.windowing.plugins-1.0.0] startup
2024-01-21 13:16:43 [169ms] [Warning] [carb.windowing-glfw.plugin] GLFW initialization failed.
2024-01-21 13:16:43 [170ms] [Warning] [carb] Failed to startup plugin carb.windowing-glfw.plugin (interfaces: [carb::windowing::IGLContext v1.0],[carb::windowing::IWindowing v1.3]) (impl: carb.windowing-glfw.plugin)
[0.183s] [ext: omni.kit.renderer.init-0.0.0] startup
2024-01-21 13:16:43 [236ms] [Warning] [carb.windowing-glfw.plugin] GLFW initialization failed.
2024-01-21 13:16:43 [236ms] [Warning] [carb] Failed to startup plugin carb.windowing-glfw.plugin (interfaces: [carb::windowing::IGLContext v1.0],[carb::windowing::IWindowing v1.3]) (impl: carb.windowing-glfw.plugin)
2024-01-21 13:16:43 [236ms] [Error] [carb.glinterop.plugin] GLInteropContext::init: carb::windowing is not available
2024-01-21 13:16:43 [236ms] [Warning] [gpu.foundation.plugin] Skipping unsupported non-RTX GPU: NVIDIA GeForce GTX 1050 Ti
2024-01-21 13:16:43 [236ms] [Warning] [gpu.foundation.plugin] Skipping unsupported non-RTX GPU: NVIDIA GeForce GTX 1050 Ti

|---------------------------------------------------------------------------------------------|
| Driver Version: 470.223.2     | Graphics API: Vulkan
|=============================================================================================|
| GPU | Name                             | Active | LDA | GPU Memory | Vendor-ID | LUID       |
|     |                                  |        |     |            | Device-ID | UUID       |
|---------------------------------------------------------------------------------------------|
| 0   | NVIDIA GeForce RTX 3080          | Yes: 0 |     | 10486   MB | 10de      | 0          |
|     |                                  |        |     |            | 2216      | e687e32a.. |
|---------------------------------------------------------------------------------------------|
| 1   | NVIDIA GeForce GTX 1050 Ti       |        |     | 4342    MB | 10de      | 0          |
|     |                                  |        |     |            | 1c82      | 8eddf50b.. |
|=============================================================================================|
| OS: Linux alicander, Version: 5.4.0-169-generic
| Processor: AMD Ryzen Threadripper 1900X 8-Core Processor   | Cores: Unknown | Logical: 16
|---------------------------------------------------------------------------------------------|
| Total Memory (MB): 31952 | Free Memory: 27894
| Total Page/Swap (MB): 2047 | Free Page/Swap: 2047
|---------------------------------------------------------------------------------------------|
[INFO] [omnigibson] ---------- Starting OmniGibson ----------
[Warning] [omni.isaac.kit.simulation_app] Modules: ['omnigibson', 'omnigibson.macros', 'omni', 'omni.kit.app._impl.telemetry_helpers'] were loaded before SimulationApp was started and might not be loaded correctly.
[Warning] [omni.isaac.kit.simulation_app] Please check to make sure no extra omniverse or pxr modules are imported before the call to SimulationApp(...)
Starting kit application with the following args:  ['/isaac-sim/exts/omni.isaac.kit/omni/isaac/kit/simulation_app.py', '/isaac-sim/apps/omni.isaac.sim.python.kit', '--/app/tokens/exe-path=/isaac-sim/kit', '--/persistent/app/viewport/displayOptions=3094', '--/rtx/materialDb/syncLoads=True', '--/rtx/hydra/materialSyncLoads=True--/omni.kit.plugin/syncUsdLoads=True', '--/app/renderer/resolution/width=1280', '--/app/renderer/resolution/height=720', '--/app/window/width=1440', '--/app/window/height=900', '--/renderer/multiGpu/enabled=False', '--/app/fastShutdown=True', '--ext-folder', '/isaac-sim/exts', '--ext-folder', '/isaac-sim/apps', '--/physics/cudaDevice=0', '--portable', '--no-window', '--allow-root']
Passing the following args to the base kit application:  []
[Warning] [omni.kit.app.plugin] No crash reporter present, dumps uploading isn't available.
[Info] [carb] Logging to file: /isaac-sim/kit/logs/Kit/Isaac-Sim/2022.2/kit_20240121_131643.log
2024-01-21 13:16:43 [1ms] [Warning] [omni.ext.plugin] [ext: omni.drivesim.sensors.nv.lidar] Extensions config 'extension.toml' doesn't exist '/isaac-sim/exts/omni.drivesim.sensors.nv.lidar' or '/isaac-sim/exts/omni.drivesim.sensors.nv.lidar/config'
2024-01-21 13:16:43 [2ms] [Warning] [omni.ext.plugin] [ext: omni.drivesim.sensors.nv.radar] Extensions config 'extension.toml' doesn't exist '/isaac-sim/exts/omni.drivesim.sensors.nv.radar' or '/isaac-sim/exts/omni.drivesim.sensors.nv.radar/config'
[0.133s] [ext: omni.stats-0.0.0] startup
[0.164s] [ext: omni.rtx.shadercache-1.0.0] startup
[0.170s] [ext: omni.assets.plugins-0.0.0] startup
[0.172s] [ext: omni.gpu_foundation-0.0.0] startup
2024-01-21 13:16:43 [164ms] [Warning] [carb] FrameworkImpl::setDefaultPlugin(client: omni.gpu_foundation_factory.plugin, desc : [carb::graphics::Graphics v2.11], plugin : carb.graphics-vulkan.plugin) failed. Plugin selection is locked, because the interface was previously acquired by: 
[0.182s] [ext: carb.windowing.plugins-1.0.0] startup
2024-01-21 13:16:43 [169ms] [Warning] [carb.windowing-glfw.plugin] GLFW initialization failed.
2024-01-21 13:16:43 [170ms] [Warning] [carb] Failed to startup plugin carb.windowing-glfw.plugin (interfaces: [carb::windowing::IGLContext v1.0],[carb::windowing::IWindowing v1.3]) (impl: carb.windowing-glfw.plugin)
[0.183s] [ext: omni.kit.renderer.init-0.0.0] startup
2024-01-21 13:16:43 [236ms] [Warning] [carb.windowing-glfw.plugin] GLFW initialization failed.
2024-01-21 13:16:43 [236ms] [Warning] [carb] Failed to startup plugin carb.windowing-glfw.plugin (interfaces: [carb::windowing::IGLContext v1.0],[carb::windowing::IWindowing v1.3]) (impl: carb.windowing-glfw.plugin)
2024-01-21 13:16:43 [236ms] [Error] [carb.glinterop.plugin] GLInteropContext::init: carb::windowing is not available
2024-01-21 13:16:43 [236ms] [Warning] [gpu.foundation.plugin] Skipping unsupported non-RTX GPU: NVIDIA GeForce GTX 1050 Ti
2024-01-21 13:16:43 [236ms] [Warning] [gpu.foundation.plugin] Skipping unsupported non-RTX GPU: NVIDIA GeForce GTX 1050 Ti

|---------------------------------------------------------------------------------------------|
| Driver Version: 470.223.2     | Graphics API: Vulkan
|=============================================================================================|
| GPU | Name                             | Active | LDA | GPU Memory | Vendor-ID | LUID       |
|     |                                  |        |     |            | Device-ID | UUID       |
|---------------------------------------------------------------------------------------------|
| 0   | NVIDIA GeForce RTX 3080          | Yes: 0 |     | 10486   MB | 10de      | 0          |
|     |                                  |        |     |            | 2216      | e687e32a.. |
|---------------------------------------------------------------------------------------------|
| 1   | NVIDIA GeForce GTX 1050 Ti       |        |     | 4342    MB | 10de      | 0          |
|     |                                  |        |     |            | 1c82      | 8eddf50b.. |
|=============================================================================================|
| OS: Linux alicander, Version: 5.4.0-169-generic
| Processor: AMD Ryzen Threadripper 1900X 8-Core Processor   | Cores: Unknown | Logical: 16
|---------------------------------------------------------------------------------------------|
| Total Memory (MB): 31952 | Free Memory: 27894
| Total Page/Swap (MB): 2047 | Free Page/Swap: 2047
|---------------------------------------------------------------------------------------------|
[1.120s] [ext: omni.kit.pipapi-0.0.0] startup
[1.138s] [ext: omni.kit.pip_archive-0.0.0] startup
[1.158s] [ext: omni.kit.loop-isaac-1.0.0] startup
[1.159s] [ext: omni.kit.async_engine-0.0.0] startup
[1.161s] [ext: omni.kit.test-0.0.0] startup
[1.302s] [ext: omni.usd.config-1.0.0] startup
[1.309s] [ext: omni.usd.libs-1.0.0] startup
[1.495s] [ext: omni.isaac.core_archive-2.0.1] startup
[1.609s] [ext: omni.pip.torch-1_13_0-0.1.4] startup
[1.614s] [ext: omni.isaac.ml_archive-1.1.0] startup
[1.716s] [ext: omni.client-0.1.1] startup
[1.728s] [ext: omni.appwindow-1.0.1] startup
...
[7.782s] [ext: omni.kit.window.stats-0.1.2] startup
[7.784s] [ext: omni.isaac.sim.python-2022.2.0] startup
[7.785s] Simulation App Starting
[10.859s] app ready
[11.117s] RTX ready
[11.117s] RTX ready
[11.217s] Simulation App Startup Complete
[11.238s] [ext: omni.usd.schema.flow-104.1.6] startup
[11.239s] [ext: omni.vdb_timesample_editor-0.1.4] startup
[11.244s] [ext: omni.slangnode-104.1.9] startup
[11.251s] [ext: omni.flowusd-104.1.9] startup
[11.403s] [ext: omni.scene.visualization.core-104.2.2] startup
[11.415s] [ext: omni.ramp-104.1.3] startup
[11.421s] [ext: omni.particle.system.core-104.7.18] startup
[11.440s] [ext: omni.particle.system.ui-104.4.12] startup
[11.707s] [ext: omni.graph.window.particle.system-104.5.2] startup
[11.758s] [ext: omni.particle.system.bundle-104.2.24] startup
[WARNING] [omnigibson.transition_rules] Cannot find recipe file at /micromamba/envs/omnigibson/lib/python3.7/site-packages/bddl/generated_data/transition_rule_recipes.json. Skipping importing recipes.
2024-01-21 13:27:17 [13,790ms] [Warning] [carb.flatcache.plugin] UsdRelationship /Render/RenderProduct_omni_kit_widget_viewport_ViewportTexture_0.orderedVars has multiple targets, which is not supported


                   ____________
                  /          / \
                 /          / /__
                /          / /  /\
               /__________/ /__/  \
               \   _____  \ \__\  /
                \  \  / \  \ \_/ /
                 \  \/___\  \   /
                  \__________\_/  
       ___                  _  ____ _ _                     
      / _ \ _ __ ___  _ __ (_)/ ___(_) |__  ___  ___  _ __  
     | | | | '_ ` _ \| '_ \| | |  _| | '_ \/ __|/ _ \| '_ \ 
     | |_| | | | | | | | | | | |_| | | |_) \__ \ (_) | | | |
      \___/|_| |_| |_|_| |_|_|\____|_|_.__/|___/\___/|_| |_|

[INFO] [omnigibson] ---------- Welcome to OmniGibson! ----------
[INFO] [omnigibson] Demo /omnigibson-src/omnigibson/examples/scenes/scene_selector.py
    ********************************************************************************
    Description:

    Prompts the user to select any available interactive scene and loads a turtlebot into it.
    It steps the environment 100 times with random actions sampled from the action space,
    using the Gym interface, resetting it 10 times.
    ********************************************************************************

Here is a list of available scene types:

[1] InteractiveTraversableScene: Procedurally generated scene with fully interactive objects

Choose a scene type (enter a number from 1 to 1): 

...
```

The error seems to be:
```
2024-01-21 13:16:43 [236ms] [Error] [carb.glinterop.plugin] GLInteropContext::init: carb::windowing is not available
```
And there are a few GLFW-related warning messages before. 

How to deal with this? Does this mean the docker image doesn't have ll it's needed to run OmniGibson? 

Help appreciated!

**Comment by cgokmen** [comment] 2024-01-21 21:52
Hi, how are you running the docker container? Make sure you are running it using our run_docker script and *without* the -h argument that runs everything in headless mode. Also keep an eye out for an error that might pop up when you run the run_docker script: if there's anything related to xhost please paste it here so we can help debug. What's your OS / window manager / etc?

**Comment by cgokmen** [comment] 2024-01-21 21:53
Also if the issue is not removing the -h argument, feel free to join our discord channel using the link on the repo's homepage - you can just post on the support channel there and we can stay in touch a bit faster.

**Comment by ChengshuLi** [comment] 2024-07-16 21:51
Closing the issue for now, feel free to reopen if there are further questions!

**Closed by ChengshuLi** 2024-07-16 21:51 UTC
Labels: question
